BUILD=build
UTEST=OFF
UDOC=ON
UEXAMPLES=OFF
CMAKE_ARGS:=$(CMAKE_ARGS)

all:
	@mkdir -p $(BUILD)
	@cd $(BUILD); cmake .. -DBUILD_TEST=$(UTEST) -DBUILD_DOC=$(UDOC) -DBUILD_EXAMPLES=$(UEXAMPLES) -DCMAKE_BUILD_TYPE=Release $(CMAKE_ARGS) && $(MAKE)

debug:
	@mkdir -p $(BUILD)
	@cd $(BUILD); cmake .. -DBUILD_TEST=$(UTEST) -DBUILD_DOC=$(UDOC) -DBUILD_EXAMPLES=$(UEXAMPLES) -DCMAKE_BUILD_TYPE=Debug $(CMAKE_ARGS) && $(MAKE)

apps:
	@$(MAKE) all UEXAMPLES=ON UTIMER=ON

debug_apps:
	@$(MAKE) debug UEXAMPLES=ON UTIMER=ON

clean:
	@rm -rf $(BUILD)
